name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: false

  build:
    needs: create-release
    if: always()
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: 0
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v6
      - name: Show workflow information
        id: get_filename
        run: |
          export _NAME=$(jq ".[\"$GOOS-$GOARCH$GOARM$GOMIPS\"].friendlyName" -r < .github/build/friendly-filenames.json)
          echo "GOOS: $GOOS, GOARCH: $GOARCH, GOARM: $GOARM, GOMIPS: $GOMIPS, RELEASE_NAME: $_NAME"
          echo "ASSET_NAME=$_NAME" >> "$GITHUB_OUTPUT"
          echo "ASSET_NAME=$_NAME" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Get project dependencies
        run: go mod download
      - name: Build Server
        run: |
          mkdir -p build_assets
          go build -v -o build_assets/server-anytls -trimpath -ldflags "-s -w" ./cmd/server
      - name: Build Mips softfloat Server
        if: matrix.goarch == 'mips' || matrix.goarch == 'mipsle'
        run: |
            GOMIPS=softfloat go build -v -o build_assets/server-anytls-softfloat -trimpath -ldflags "-s -w" ./cmd/server
      - name: Rename Windows Server
        if: matrix.goos == 'windows'
        run: |
          cd ./build_assets || exit 1
          mv server-anytls server-anytls.exe
      - name: Prepare to release
        run: |
          cp ${GITHUB_WORKSPACE}/README.md ./build_assets/README.md
          cp ${GITHUB_WORKSPACE}/LICENSE ./build_assets/LICENSE
      - name: Create ZIP archive
        shell: bash
        run: |
          pushd build_assets || exit 1
          touch -mt $(date +%Y01010000) *
          zip -9vr ../server-anytls-$ASSET_NAME.zip .
          popd || exit 1
          FILE=./server-anytls-$ASSET_NAME.zip
          DGST=$FILE.dgst
          for METHOD in {"md5","sha1","sha256","sha512"}
          do
            openssl dgst -$METHOD $FILE | sed 's/([^)]*)//g' >>$DGST
          done
      - name: Change the name
        run: |
          mv build_assets server-anytls-$ASSET_NAME
      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: server-anytls-${{ steps.get_filename.outputs.ASSET_NAME }}
          path: |
            ./server-anytls-${{ steps.get_filename.outputs.ASSET_NAME }}/*
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          tag_name: ${{ github.ref_name }}
          files: ./server-anytls-${{ steps.get_filename.outputs.ASSET_NAME }}.zip*
